version: "3.8"

# docker-compose to easily test API+redis locally

services:
  hubble-public-api:
    build: .
    ports:
      - "8888:8888"
    environment:
      - SERVER_PORT=8888
      - MAINNET_ENDPOINT=${MAINNET_ENDPOINT}
      - DEVNET_ENDPOINT=${DEVNET_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - COIN_STATS_TABLE=coin-stats-dev
      - API_VERSION=local-docker
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - POSTGRES_CONNECTION_STRING=postgres://hubbleUser:hubblePass@db:5432/hubble-public-api-local
    depends_on:
      - redis
      - db
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hubbleUser
      - POSTGRES_PASSWORD=hubblePass
      - POSTGRES_DB=hubble-public-api-local
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:8.5.4-alpine
#    image: hubbleprotocol/hubble-public-api-migrations:latest
#    build:
#      context: migrations
#      dockerfile: ./Dockerfile
    command: migrate
    depends_on:
      - db
    environment:
      - MIGRATION_POSTGRES_USER=hubbleUser
      - MIGRATION_POSTGRES_PASSWORD=hubblePass
      - MIGRATION_POSTGRES_URL=jdbc:postgresql://db:5432/hubble-public-api-local
    volumes:
      - ./migrations/sql:/flyway/sql
      - ./migrations/conf:/flyway/conf