export const STAKING_STATS_EXPIRY_IN_SECONDS = 5 * 60;
export const CIRCULATING_SUPPLY_EXPIRY_IN_SECONDS = 60;
export const MAINTENANCE_MODE_EXPIRY_IN_SECONDS = 60;
export const BORROWING_VERSION_EXPIRY_IN_SECONDS = 60;
