import { BORROWING_IDL } from '@hubbleprotocol/hubble-idl';
import Router from 'express-promise-router';
import { Request } from 'express';

/**
 * Get Hubble IDL generated by Anchor
 */
const idlRoute = Router();
idlRoute.get('/', (request: Request<never, any[], never, never>, response) => {
  const idls = [BORROWING_IDL]; // add other IDLs in the future...
  return response.send(idls);
});

export default idlRoute;
