service-base-chart:
  applicationName: hubble-public-api
  image:
    repository: hubbleprotocol/hubble-public-api
    tag: "latest"

  initContainers:
    - name: hubble-public-api-migrations
      image: hubbleprotocol/hubble-public-api-migrations:latest
      imagePullPolicy: Always
      args: ['migrate']
      env:
        - name: MIGRATION_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: hubble-public-api-secret
              key: MIGRATION_POSTGRES_USER
        - name: MIGRATION_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hubble-public-api-secret
              key: MIGRATION_POSTGRES_PASSWORD
        - name: MIGRATION_POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: hubble-public-api-secret
              key: MIGRATION_POSTGRES_URL

  containerPorts:
    - name: http
      containerPort: 80
      protocol: TCP

  startupProbe:
    path: /version
  livenessProbe:
    path: /version
  readinessProbe:
    path: /health

  autoscaling:
    targetCPUUtilizationPercentage: 60
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 600
        policies:
          - type: Percent
            value: 10
            periodSeconds: 60

  envVars:
    - name: SERVER_PORT
      value: "80"
    - name: MAINNET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: MAINNET_ENDPOINT
    - name: DEVNET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: DEVNET_ENDPOINT
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: AWS_SECRET_ACCESS_KEY
    - name: POSTGRES_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: POSTGRES_CONNECTION_STRING
    - name: COIN_STATS_TABLE
      value: "coin-stats-dev"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_HOST
      value: "redis-hubble-public-api-master"
    - name: POSTGRES_POOL_MIN
      value: "1"

  secrets:
    MAINNET_ENDPOINT:
    DEVNET_ENDPOINT:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    # below are required for flyway migrations (connection string form differs slightly...):
    MIGRATION_POSTGRES_USER:
    MIGRATION_POSTGRES_PASSWORD:
    MIGRATION_POSTGRES_URL: # example: jdbc:postgresql://host:5432/dbName
    # required for API:
    POSTGRES_CONNECTION_STRING: # example: postgres://user:pass@host:5432/dbName

redis:
  architecture: replication
  fullnameOverride: redis-hubble-public-api
  master:
    extraFlags:
      - "--maxmemory-policy allkeys-lru"
  auth:
    enabled: false

