service-base-chart:
  applicationName: hubble-public-api
  image:
    repository: hubbleprotocol/hubble-public-api
    tag: "latest"

  containerPorts:
    - name: http
      containerPort: 80
      protocol: TCP

  startupProbe:
    path: /version
  livenessProbe:
    path: /version
  readinessProbe:
    path: /health

  envVars:
    - name: SERVER_PORT
      value: "80"
    - name: MAINNET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: MAINNET_ENDPOINT
    - name: DEVNET_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: DEVNET_ENDPOINT
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: hubble-public-api-secret
          key: AWS_SECRET_ACCESS_KEY
    - name: COIN_STATS_TABLE
      value: "coin-stats-dev"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_HOST
      value: "redis-hubble-public-api-master"

  secrets:
    MAINNET_ENDPOINT:
    DEVNET_ENDPOINT:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:

redis:
  architecture: standalone
  fullnameOverride: redis-hubble-public-api
  auth:
    enabled: false

