name: Hubble Public API Docker Build

on:
  push:
    branches:
      - express # todo: remove after merged to master..
#      - master

jobs:
  build_docker:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.set_versions.outputs.build_version }}
      release_version: ${{ steps.set_versions.outputs.release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.HUBBLE_GITHUB_DEPLOY_KEY }}
      - name: Set versions
        id: set_versions
        shell: bash
#        working-directory: ./bots/liquidations-bot
        run: ./.github/scripts/set-node-versions.sh
      - name: Docker buildx (build)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          file: ./Dockerfile
          tags: hubbleprotocol/hubble-public-api:${{ steps.set_versions.outputs.build_version }}
          push: true
          target: release
          cache-from: type=gha
          cache-to: type=gha,mode=min
          build-args: |
            "API_VERSION=${{ needs.build_docker.outputs.release_version }}"
  build_helm:
    needs: build_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Helm build
        id: helm_build
        uses: docker/build-push-action@v2
        with:
          file: ./.github/docker/helm.Dockerfile
          tags: hubbleprotocol/hubble-public-api-helm-build:${{ needs.build_docker.outputs.build_version }}
          push: false
          secrets: |
            "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID_HELM_REPO }}"
            "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY_HELM_REPO }}"
          build-args: |
            "CHART=hubble-public-api"
            "BUILD_VERSION=${{ needs.build_docker.outputs.build_version }}"
  pre_release:
    needs:
      - build_docker
      - build_helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Fetch release artifact
        id: fetch_release_bin
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: hubbleprotocol/hubble-public-api-release-bin:${{ needs.build_docker.outputs.build_version }}
          push: false
          target: release-bin
          outputs: "type=tar,dest=hubble-public-api-${{ needs.build_docker.outputs.build_version }}.tar"
          cache-from: type=gha
      - name: Create pre-release
        id: pre_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: hubble-public-api/${{ needs.build_docker.outputs.release_version }}
          prerelease: true
          title: hubble-public-api/${{ needs.build_docker.outputs.release_version }}
          files: |
            hubble-public-api-*.tar